Reorganize macro buttons
Thorium-Sim/thorium pull request #3225
Opened 2022-02-11 22:02 UTC by SoshJam

## Description

Added functionality to rearrange the order in which a macro executes its assigned actions. Create a macro button with more than one action, then click and drag the actions to rearrange them.

## Related Issue

https://github.com/Thorium-Sim/thorium/issues/3201

## Screenshots (if appropriate):

- [ ] I submitted a pull request or created an issue for documenting this
      feature on the [Thorium Docs](https://github.com/Thorium-Sim/thorium-docs)
      repo. (Include the issue or pull request url below.)

2022-02-12 00:56 UTC, alexanderson1993 requested changes
The code that you've written is good, but I have to reject this PR as it is right now for two reasons.

- Not a big deal, but you shouldn't be putting your name all over the code. Add yourself to the .all-contributorsrc file, include yourself in the credits in the src/components/client/credits.ts file, but don't put your name next to every piece of code you write.


- This is the biggest reason: Your PR makes it possible to reorganize the actions, not the buttons themselves. The linked issue requests the ability to reorder the buttons. In the attached screenshot, the list on the left is the one that should be reordered, not the one on the left.


<img width="1040" alt="Screen Shot 2022-02-11 at 7 55 34 PM" src="https://user-images.githubusercontent.com/6558157/153689448-a1d0985a-57f8-42bb-8676-da210c47cf31.png">

Take care of those two things and I'd be happy to merge this.

2022-02-12 00:56 UTC, alexanderson1993 commented on server/events/eventMacro.js
> +// Reorder Macro Action by Sam Hill
There's no need to leave your signature everywhere - it's already included as part of the git history.

2022-02-12 00:56 UTC, alexanderson1993 commented on src/containers/FlightDirector/MacroButtons/macroConfig.js
> +      {/* Old macro action list
If you've commented out all of the old code that you've replaced, you should probably just delete that code anyway.

2022-02-15 23:18 UTC, SoshJam commented
Changes should be complete.

2022-02-16 00:13 UTC, alexanderson1993 commented
LGTM. Nice work.

2022-02-16 00:13 UTC, merged